---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    
  pre_tasks:
    - name: "wait for 600 seconds for server to come online"
    - name: "install python runtime"
      apt:
        name: python3
        update_cache: yes
  
  destroy-environment:
    - NODE_ENV: production
    - VERSION: "0.1"
    
  roles:
    - deploy
