---
- name: "download and prepare required packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: Install NodeJS
  become: true
  shell: |
    apt update
    apt install nodejs npm

- name: Install Pm2
  become: true
  shell: |
    npm install pm2 -g && pm2 update
    pm2 completion install
 
